### ISSUE TITLE
minids instructions miss requirement for globus_sdk

### ISSUE THREAD

**Issue by lliming** [fair-research/fair-metadata-tools#4]
I had to install the globus_sdk before I was able to use the globus-identifier-client, even after it was installed successfully.  (I had a Python 2.7 version of globus_sdk but it wasn't in my Python 3.6 environment.)  Might want to update the installation and/or the instructions to make sure that's covered.

**Comment by NickolausDS** [comment]
I may as well also add instructions on creating a virtualenv so not to assume folks are already doing that, so it doesn't cause any havoc on their installed packages.
